spring.datasource.url=jdbc:mysql://localhost:3306/UserAuth
spring.datasource.username=root
spring.datasource.password=@fullstackDev_0562
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080